version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elastic
    environment:
      ES_JAVA_OPTS: '-Xms256m -Xmx256m'
      network.bind_host: 0.0.0.0
      network.host: 0.0.0.0
      discovery.type: single-node
  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1
    volumes:
      - kibanadata:/usr/share/kibana/data
    ports:
      - 5601:5601
    networks:
      - elastic
volumes:
  esdata:
    driver: local
  kibanadata:
    driver: local
networks:
  elastic:
    driver: bridge